// Code generated by "stringer -type CardValue"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[V_Joker-0]
	_ = x[V_A-1]
	_ = x[V_1-2]
	_ = x[V_2-3]
	_ = x[V_3-4]
	_ = x[V_4-5]
	_ = x[V_5-6]
	_ = x[V_6-7]
	_ = x[V_7-8]
	_ = x[V_8-9]
	_ = x[V_9-10]
	_ = x[V_10-11]
	_ = x[V_J-12]
	_ = x[V_Q-13]
	_ = x[V_K-14]
}

const _CardValue_name = "V_JokerV_AV_1V_2V_3V_4V_5V_6V_7V_8V_9V_10V_JV_QV_K"

var _CardValue_index = [...]uint8{0, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 41, 44, 47, 50}

func (i CardValue) String() string {
	if i < 0 || i >= CardValue(len(_CardValue_index)-1) {
		return "CardValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardValue_name[_CardValue_index[i]:_CardValue_index[i+1]]
}
