// Code generated by "stringer --type CardSuit"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SJoker-0]
	_ = x[SSpades-1]
	_ = x[SDiamonds-2]
	_ = x[SClubs-3]
	_ = x[SHearts-4]
}

const _CardSuit_name = "SJokerSSpadesSDiamondsSClubsSHearts"

var _CardSuit_index = [...]uint8{0, 6, 13, 22, 28, 35}

func (i CardSuit) String() string {
	if i < 0 || i >= CardSuit(len(_CardSuit_index)-1) {
		return "CardSuit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardSuit_name[_CardSuit_index[i]:_CardSuit_index[i+1]]
}
